### ISSUE TITLE
Starting websockets transport fails

### ISSUE THREAD

**Issue by Chartman123** [canyanio/janus-gateway-docker#5]
Since a few days I can't get the latest ":master" Docker image running because of some missing symbols (lws_write_ws_flags). 

```
Janus commit: 4614b6b2b43031bcde457b9bd9b65e8a364d6f52
Compiled on:  Sat Sep 26 04:12:10 UTC 2020

Logger plugins folder: /usr/local/lib/janus/loggers
[WARN] 	Couldn't access logger plugins folder...
---------------------------------------------------
  Starting Meetecho Janus (WebRTC Server) v0.10.6

[...]

Loading transport plugin 'libjanus_websockets.so'...,
[ERR] [janus.c:main:5216] 	Couldn't load transport plugin 'libjanus_websockets.so': /usr/local/lib/janus/transports/libjanus_websockets.so: undefined symbol: lws_write_ws_flags
```

I tracked it down to a change in the janus-gateway repository:

https://github.com/meetecho/janus-gateway/blob/4614b6b2b43031bcde457b9bd9b65e8a364d6f52/transports/janus_websockets.c#L1245

https://github.com/meetecho/janus-gateway/commit/8b9549a3bf87dd79d521b18c5770f2a4696a651a

Is it possible that you're using an older libwebsockets that doesn't contain lws_write_ws_flags?

**Comment by tranchitella** [comment]
@Chartman123 the Docker image is using buster's version of libwebsockets (4.0). Upstream release 4.1, I'll try to manually download and use the updated version instead.

**Comment by tranchitella** [comment]
@Chartman123 would you mind trying the latest master and check if the problem persists?

**Comment by Chartman123** [comment]
With the latest master image I get the following errors:

    Loading transport plugin 'libjanus_websockets.so'...
    [ERR] [janus.c:main:5306] 	Couldn't load transport plugin 'libjanus_websockets.so': libwebsockets.so.16: cannot open shared object file: No such file or directory,
    [FATAL] [janus.c:main:5368] No Janus API transport is available... enable at least one and restart Janus,

**Comment by tranchitella** [comment]
@Chartman123 would you mind trying again? In case it files, can you please share your config file?

**Comment by Chartman123** [comment]
The latest image is running fine. Thank you for fixing it 👍

**Comment by Chartman123** [comment]
Btw. are there any plans on providing versioned tags for the newer Janus versions, too, or was 0.9(.2) the last one?

**Comment by tranchitella** [comment]
@Chartman123 I published version 0.9.5 (latest of 0.9 branch) and 0.10.7 (latest stable release)

**Comment by Chartman123** [comment]
Ok, thank you :) Does this 0.10.7 also include the fix for the websockets? Otherwise I will stick to master, which includes 0.10.8 iirc.

**Comment by tranchitella** [comment]
@Chartman123 yes it does, it is built using the same Dockerfile.
